// <auto-generated />
using System;
using JSFC.HeldenTaverne.Persistence;
using JustGideon.DSA5CharacterManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustGideon.DSA5CharacterManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231025091037_AddCast")]
    partial class AddCast
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JustGideon.DSA5CharacterManager.Domain.Entities.WeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("JustGideon.DSA5CharacterManager.Domain.MasterData.Casts.Cast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AsPKosten")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Feature")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reichweite")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Verbreitung")
                        .HasColumnType("int");

                    b.Property<string>("WirkungDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("WirkungIdentifier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Wirkungsdauer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Zauberdauer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Zielkategorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Casts");
                });
#pragma warning restore 612, 618
        }
    }
}
